version: '3'

services:
  web:
    build: ./nginx
    ports:
      - '8080:80'
    networks:
      - webnet
    depends_on:
      - backend
  backend:
    build: .
    ports:
      - '2080:2080'
    networks:
      - webnet

networks:
  webnet:
