name: VX CICD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Deploying to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd vx-website/vx-website-backend
            git pull
            npm prune --force
            npm install --force
            npm run build
            pm2 reload all
